### ISSUE TITLE
multiple screen (bad result with multiple maximised windows)

### ISSUE THREAD

**Issue by NNois** [pixel-saver/pixel-saver#105] opened 2017-01-15 23:49 UTC
Hi,
The extension is very usefull but currently if you have multiple screens the extension remove also the titlebar of windows who aren't on a screen with the gnome top bar.

Could it be possible to disable the extension for windows out of the primary screen or the one with the top bar ?

thanks

**Comment by afranke** [comment] 2017-03-14 17:04
Duplicate of #80.

**Comment by tallero** [comment] 2020-10-12 14:09
@NNois use pixel saver with multimonitor addon.

**Closed** 2020-10-12 14:10 UTC
Labels: duplicate, enhancement, workaround
