### ISSUE TITLE
Severe Full Display Freezes when using Pixel Saver under wayland.

### ISSUE THREAD

**Issue by bluelightzero** [pixel-saver/pixel-saver#155] opened 2018-02-27 10:26 UTC
Easy to reproduce open gnome-terminal with plugin enabled.

Click on any Menu Item (File, Edit, View, ect)

Move your mouse back and forth left to right. (File -> Edit -> File -> Edit)

Your entire computer screen, including mouse will now freeze temporarily. (Play an video in background to test)

This doesn't effect all applications (Firefox) but lots of important ones (nautilus, terminal)

Related Issue, seem to affect a few plugins: https://bugzilla.redhat.com/show_bug.cgi?id=1218402

**Comment by matthiasb85** [comment] 2018-02-28 08:36
I can confirm that behavior. My current setup is an Intel 2gen core i5 with integrated graphics running gnome 3.26.2 on Arch Linux.

**Comment by deadalnix** [comment] 2018-03-09 19:35
Wayland is not really well supported by pixel saver, sadly. There is no good API to do so. I'd be happy to merge something if someone has a good idea how to do it.

**Comment by tallero** [comment] 2019-09-03 14:27
Closing this because it is related to #32

**Closed by tallero** 2019-09-03 14:27 UTC
