### ISSUE TITLE
Doesn't work on ubuntu 19.04

### ISSUE THREAD

**Issue by eren000** [pixel-saver/pixel-saver#200] opened 2019-04-24 09:14 UTC
receive an error on ubuntu 19.04 & gnome-shell  3.32.0

**Comment by matthijskooijman** [comment] 2019-05-05 14:45
This is a duplicate of #195.

**Comment by tallero** [comment] 2019-09-02 20:02
It works since https://github.com/pixel-saver/pixel-saver/commit/3e6b39572aceb8aedfee878c1081482d73c7c2ec.

**Closed by tallero** 2019-09-02 20:02 UTC
