### ISSUE TITLE
Option to only function on the primary display

### ISSUE THREAD

**Issue by zachbr** [pixel-saver/pixel-saver#77] opened 2016-05-31 03:13 UTC
Currently this applies to all displays, or no displays. I would appreciate an option to only have this happen on the user's primary display. I'm not familiar with gnome extensions so apologies if there are any technical hurdles in the way of this.

**Comment by bittner** [comment] 2017-11-05 20:43
Duplicate of #80.

**Closed** 2019-09-03 18:54 UTC
