### ISSUE TITLE
Ability to select the position of the buttons

### ISSUE THREAD

**Issue by Kalugin-Roman** [pixel-saver/pixel-saver#210] opened 2020-05-07 11:13 UTC
Please add the ability to place buttons in different places on the panel. For example, as done in this extension https://extensions.gnome.org/extension/1267/no-title-bar/

Unfortunately, many give up support for their work :(  I hope you are still interested. Thank!

**Comment by tallero** [comment] 2020-06-27 14:56
duplicate of #122

**Closed by tallero** 2020-06-27 14:56 UTC
Labels: duplicate
