### ISSUE TITLE
Not working with Terminal, Tilix, ...

### ISSUE THREAD

**Issue by ddnexus** [pixel-saver/pixel-saver#118] opened 2017-04-17 01:20 UTC
A few apps are not affected by the extension. 

Ubuntu GNOME 17.10 (wayland)

**Comment by vadzimt** [comment] 2017-04-19 09:33
Doesn't work with default terminal app on Fedora 25 (gnome-desktop 3.22.2, wayland session). The rest like Wireshark, Kcachegrind, etc are fine.

**Comment by cj-sv** [comment] 2017-07-05 09:33
Confirmed here as well, doesn't work in GNOME Shell 3.24.2 on Wayland session. Works just fine on GNOME Classic.

**Comment by mnuke** [comment] 2017-09-23 08:12
I think this is a duplicate of #32

**Comment by jhasse** [comment] 2017-09-25 07:13
If you want this fixed, please express your support of merging the patch for Gtk3 here: https://bugzilla.gnome.org/show_bug.cgi?id=775061

**Comment by lvitals** [comment] 2017-10-15 15:42
Disable  client-side decorations, install gtk3-nocsd this package is already in the main branch of Debian and Ubuntu 17.10

**Comment by franglais125** [comment] 2017-10-15 15:44
@lvitals gnome-terminal doesn't use CSD...

**Comment by lvitals** [comment] 2017-10-15 16:03
@franglais125 apparently not, but I'm using Ubuntu 17.10 and the extension did not work for gnome-terminal until I installed the gtk3-nocsd

**Comment by franglais125** [comment] 2017-10-15 16:08
@lvitals two possible explanations for that:
1. are you using Wayland or Xorg?
2. gnome-terminal uses XWayland with the nocsd package.

**Comment by lvitals** [comment] 2017-10-15 16:19
@franglais125 I'm using wayland

$ loginctl show-session 2 -p Type
Type=wayland

**Comment by lvitals** [comment] 2017-10-15 19:37
@franglais125 for gtk3-nocsd to work on wayland I needed to add in /etc/environment
GDK_BACKEND=x11
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0 
GTK_CSD=0 
For those who are using Xorg don't add command line in /etc/environment because there were boot problems.

**Comment by franglais125** [comment] 2017-10-15 19:51
> `GDK_BACKEND=x11`

This is what I was saying, you are running the terminal through XWayland, hence why pixel-saver works on it.

**Comment by tallero** [comment] 2019-09-03 18:35
Pixel saver works with X11 applications or XWayland applications in Wayland sessions, so everything that runs as native wayland window will not work.

**Closed by tallero** 2019-09-03 18:35 UTC
