### ISSUE TITLE
title buttons

### ISSUE THREAD

**Issue by dirosis** [pixel-saver/pixel-saver#116] opened 2017-04-12 10:05 UTC
Generally the extension works pretty well but since the last update the buttons theme requires a shell restart to be applied. 
It would also be amazing if the buttons of gtk apps where also integrated in the top bar as in unity (rip) but I understand it would be pretty difficult to happen
P.S I've created a button theme for zukitre if someone is interested

**Comment by tallero** [comment] 2019-09-03 18:42
>Generally the extension works pretty well but since the last update the buttons theme requires a shell restart to be applied.

#132  is a duplicate of this, but there has been added more useful content to solve the bug, so I am closing this one.

 >It would also be amazing if the buttons of gtk apps where also integrated in the top bar as in unity (rip) but I understand it would be pretty difficult to happen

What do you mean?

**Closed by tallero** 2019-09-03 18:42 UTC
