### ISSUE TITLE
Whitelist and blacklist working modes.

### ISSUE THREAD

**Issue by gazhay** [pixel-saver/pixel-saver#131] opened 2017-05-28 18:22 UTC
Allow per application settings.

e.g. only active for "x,y,z apps" or "disable for x,y,z apps"

**Comment by MichaelAquilina** [comment] 2017-05-28 18:45
I also think this would be a useful feature

**Comment by tallero** [comment] 2019-09-03 18:52
Duplicate of #86.

**Closed by tallero** 2019-09-03 18:52 UTC
Labels: duplicate
