### ISSUE TITLE
multi-monitor support

### ISSUE THREAD

**Issue by the0demiurge** [pixel-saver/pixel-saver#107] opened 2017-02-19 16:14 UTC
When using multi-monitor, the extended monitor doesn't have a top bar, which makes it hard to drag maximized window away.

**Comment by afranke** [comment] 2017-03-14 17:04
Duplicate of #80.

**Comment by bittner** [comment] 2017-11-05 20:43
Duplicate of #77 (maybe).

**Closed** 2019-09-03 18:50 UTC
