### ISSUE TITLE
Window buttons don't show when window snapped to sides

### ISSUE THREAD

**Issue by Austint30** [pixel-saver/pixel-saver#121] opened 2017-04-22 21:36 UTC
I find it quite odd the way this extension removes the titlebar of a window when it is snapped to the sides and doesn't include the window buttons in the top panel. That means in order to close or minimize a half-maximized window I have to rag down on the top panel to unmaximize and then the window buttons on the title bar are visible.

What I expect to happen when a window is snapped to the sides is the window buttons to be visible on the top panel so I can close or minimize. Alternatively, it would be better to not remove the window title bar at all when a window is snapped to the sides.

**Comment by abrandemuehl** [comment] 2017-04-23 00:22
I think this is a duplicate of #16

**Closed** 2019-09-03 18:55 UTC
