### ISSUE TITLE
Terminal title bar reappears after upgrade to Ubuntu 10.10

### ISSUE THREAD

**Issue by ntnsndr** [pixel-saver/pixel-saver#146] opened 2017-10-20 15:45 UTC
Thank you for this fantastic extension.

In GNOME with Ubuntu 10.04, this extension caused the title bar of the Terminal to disappear when in full-screen or split right/left. This was a really nice behavior. Since upgrading, the title bar has reappeared, requiring me to go into full-screen mode, which is less flexible. Is there a way to bring back the previous behavior?

Thank you for your good work.

**Comment by franglais125** [comment] 2017-10-20 23:24
This is most likely due to the fact that Ubuntu 17.10 defaults to Wayland. You can try changing the session to Xorg from the login screen.

**Comment by gsalgado** [comment] 2017-10-23 17:49
@franglais125 is right; using Xorg it still works on Ubuntu 17.10

**Comment by bittner** [comment] 2017-11-05 21:07
Looks like this doesn't only affect the Terminal application. It's kind of "half of the applications" don't allow this extension to make the window title bar disappear in Wayland.

Is this something that can be fixed in this extension?

@ntnsndr Can you correct the issue title from "10.10" to "17.10"? Also in the issue description you're mentioning "10.04", yet probably intending "17.04", correct?

**Comment by bittner** [comment] 2017-11-05 21:11
Duplicate of #32.

**Comment by franglais125** [comment] 2017-11-07 00:18
@bittner 

> It's kind of "half of the applications" don't allow this extension to make the window title bar disappear in Wayland.

It's not randomly some applications. This extension will work with XWayland applications in a Wayland session.

**Closed** 2019-09-03 14:21 UTC
